"""Apply adjudicated review fixes to knowledge/*.yaml as exact text replacements.

Every (old, new) pair must match exactly once, so a stale anchor fails loudly instead of
silently editing the wrong market. Appends a summary to review/CHANGES.md.
Run from the repo root: python review/apply_knowledge_fixes.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
K = ROOT / "knowledge"

EDITS: dict[str, list[tuple[str, str, str]]] = {
    # (old, new, finding reference)
    "markets/americas.yaml": [
        ("  basis: FMVSS (49 CFR Part 571) + EPA/CARB emissions & GHG + NHTSA CAFE",
         "  basis: FMVSS (49 CFR Part 571) + EPA/CARB criteria-pollutant emissions + NHTSA CAFE",
         "mk-01 US basis (EPA GHG standards rescinded)"),
        ('scope: "Exhaust/evap emissions, GHG, fuel-economy labels, refrigerants (SNAP)"',
         'scope: "Exhaust/evap emissions, fuel-economy test procedures & labels, refrigerants (SNAP)"',
         "mk-01 US EPA scope"),
        ('  emissions: "EPA Tier 3 → 2027+ multi-pollutant standards (light-/medium-duty); CARB LEV III → LEV IV / Advanced Clean Cars II in CA and adopting states. Status of federal waivers and ACC II enforcement has been litigated — verify current position."',
         '  emissions: "EPA Tier 3 → 2027+ criteria-pollutant standards. EPA rescinded the GHG endangerment finding and ALL federal vehicle GHG standards (final rule published 18 Feb 2026). CARB LEV III applies in California; the federal waiver for Advanced Clean Cars II (LEV IV / ZEV) was revoked by Congress under the CRA (12 Jun 2025) and is in litigation. Fuel economy: NHTSA CAFE reset for MY2022–2031 (SAFE Vehicles Rule III, FR 30 Sep 2026, effective 30 Nov 2026; credit trading eliminated)."',
         "mk-01 US emissions (verified: EPA rule, H.J.Res.88, FR 2026-19964)"),
        ('  emissions: "ECCC regulations aligned with US EPA Tier 3; GHG standards aligned with US; Electric Vehicle Availability Standard (ZEV sales targets) adopted 2023 — check for amendments/pauses."',
         '  emissions: "ECCC On-Road Vehicle and Engine Emission Regulations (aligned with US EPA Tier 3 criteria pollutants). GHG: Canada keeps its own passenger-car/light-truck GHG regulations (no longer mirrors the US after the 2026 US repeal); amendments tightening them for MY2027–2032 were proposed in Canada Gazette I (15 Aug 2026). The Electric Vehicle Availability Standard\'s 2026 target was paused (Sep 2025) and its repeal proposed (draft regulations, comments to 29 Oct 2026)."',
         "mk-01 CA emissions (verified; repeal is a draft, not final)"),
        ('    - "Electric Vehicle Availability Standard — 2026 model-year target status."',
         '    - "EVAS repeal and replacement GHG standards for MY2027–2032 (Canada Gazette I, Aug 2026) — final regulations pending."',
         "mk-01 CA watch"),
        ('    - "NOM-194 phase-in items (pedestrian protection, ESC, side impact) — verify the current applicability table."',
         '    - "NOM-194-SE-2021 phase-in: ESC and ISOFIX/LATCH mandatory from MY2025, tyre-pressure monitoring from MY2026; pedestrian protection is listed as optional equipment — verify the current applicability table."',
         "mk-01 MX watch"),
        ('  basis: "MinCIT technical regulation for vehicles (Res. 3752/2015 and successors) referencing UN R / FMVSS; Ministry of Environment emission rules"\n  un_1958: false',
         '  basis: "Ministerio de Transporte vehicle safety regulation (Res. 3752/2015 and successors) referencing UN R / FMVSS; Ministry of Environment emission rules"\n  un_1958: null',
         "mk-02 CO basis + un_1958 (Ley 2290/2023 approves accession; deposit unconfirmed)"),
        ('    - { name: "Ministerio de Comercio, Industria y Turismo (MinCIT)", scope: "Vehicle safety technical regulation (reglamento técnico)", url: "https://www.mincit.gov.co" }',
         '    - { name: Ministerio de Transporte, scope: "Vehicle active/passive safety regulation (Res. 3752/2015 and successors), RUNT registration", url: "https://www.mintransporte.gov.co" }\n    - { name: "Ministerio de Comercio, Industria y Turismo (MinCIT)", scope: "Component technical regulations (e.g. tyres)", url: "https://www.mincit.gov.co" }',
         "mk-02 CO authority"),
        ('  notes:\n    - "Many US-market vehicles are sold in Mexico on FMVSS evidence; UN R evidence is equally accepted for NOM-194 items."',
         '  notes:\n    - "Many US-market vehicles are sold in Mexico on FMVSS evidence; UN R evidence is equally accepted for NOM-194 items."',
         "noop anchor check MX notes"),
    ],
    "markets/asia_pacific.yaml": [
        ('    - "Six airbags in M1 (draft) and Bharat NCAP; AIS-189/190 for cybersecurity & software update (aligned with UN R155/156)."',
         '    - "AIS-189 / AIS-190 cybersecurity & software-update requirements (aligned with UN R155/156) — reported applicable to new types from Oct 2025; verify notification. (The 2022 six-airbag M1 proposal was not made mandatory.)"',
         "mk-03 IN watch"),
        ('  basis: "Pakistan: Motor Vehicle Safety & Quality standards (EDB / PSQCA) moving toward UN R adoption after 1958 accession; others: import/registration checks"',
         '  basis: "Pakistan: Motor Vehicle Safety & Quality standards (EDB / PSQCA) moving toward UN R adoption after its 1958 Agreement accession (E64, 2020); others: import/registration checks"',
         "mk-03 SOUTH-ASIA (Pakistan E64 verified)"),
        ('  members: [Pakistan, Bangladesh, Sri Lanka, Nepal, Bhutan, Maldives]',
         '  members: ["Pakistan (E64, 1958 CP)", Bangladesh, Sri Lanka, Nepal, Bhutan, Maldives]',
         "mk-03 SOUTH-ASIA members"),
        ('  emissions: "Euro 5 (from 2024; Euro 6 planned) — CO2-based excise tax"',
         '  emissions: "Euro 5 for newly manufactured vehicles from 1 Jan 2024; Euro 6 for gasoline light-duty vehicles from 1 Jan 2025, with later dates reported for larger petrol and diesel vehicles — verify per TIS. CO2-based excise tax."',
         "mk-04 TH emissions"),
        ('  basis: "QCVN national technical regulations (many UN R-based) — Vietnam Register (VR) under Ministry of Construction (formerly MOT) — import and domestic production certification"\n  un_1958: false',
         '  basis: "QCVN national technical regulations (many UN R-based) — Vietnam Register (VR) under Ministry of Construction (formerly MOT) — import and domestic production certification; 1958 Agreement CP since 24 Sep 2023"\n  un_1958: true',
         "mk-04 VN un_1958 (verified)"),
        ('  accepts: ["UN R approvals / test reports used as evidence for QCVN items", "ASEAN MRA"]\n  marks: ["VR certificate of technical safety and environmental protection quality"]',
         '  accepts: ["UN R approvals under the 1958 Agreement (mutual recognition being implemented — Decision 77/QD-TTg, Jan 2026)", "UN R test reports as evidence for QCVN items", "ASEAN MRA"]\n  marks: ["VR certificate of technical safety and environmental protection quality", "E-mark for UN approvals granted by Vietnam (number not verified here)"]',
         "mk-04 VN accepts/marks"),
        ('  regions: []\n  aliases: [LTA, VES, COE]', '  regions: [ASEAN]\n  aliases: [LTA, VES, COE]', "mk-04 SG regions"),
        ('    - "Identification plate no longer required post-RVSA — RAV entry replaces it; VIN per ADR 61"',
         '    - "RAV entry plus secure vehicle identification marking (ADR 61/03) replaces the compliance plate for most vehicles; trailers and some heavy vehicles still carry a physical plate"',
         "mk-05 AU marks"),
        (', au-workbook-reg-0605-radiocommunications-equipment-general-rules-2021-acma, au-f2012l01123]',
         ', au-workbook-reg-0605-radiocommunications-equipment-general-rules-2021-acma]',
         "mk-05 AU records (au-f2012l01123 superseded)"),
        ('  emissions: "Euro 6d-equivalent for new models from Dec 2025 (ADR 79/05 / ADR 111 / ADR 112 RDE); NVES CO2 targets from 2025"',
         '  emissions: "Euro 6d-equivalent (ADR 79/05, ADR 111, ADR 112 RDE) for new models from 1 Dec 2025 and all new vehicles from 1 Jul 2028; NVES fleet CO2 targets from 1 Jul 2025"',
         "mk-05 AU emissions"),
        ('  emissions: "Vehicle Exhaust Emissions Rule (Euro 6 / JP / US equivalents); Clean Car Standard CO2 targets"',
         '  emissions: "Vehicle Exhaust Emissions Rule: Euro 5 (or JP/US equivalents) currently for new light vehicles; Euro 6d phased in from 1 Jul 2027 (new models) and 1 Jul 2028 (all light vehicles incl. used imports) — verify. Clean Car Standard CO2 targets."',
         "mk-05 NZ emissions"),
        ('  notes: ["Mostly RHD (drive on left); Samoa switched to left-hand traffic in 2009; US-affiliated territories (Guam, American Samoa, N. Mariana Is.) follow US rules."]',
         '  notes: ["Mostly RHD (drive on left; Samoa switched in 2009); Vanuatu, Micronesia and Palau drive on the right; US-affiliated territories (Guam, American Samoa, N. Mariana Is.) follow US rules."]',
         "mk-05 PACIFIC drive"),
    ],
    "markets/europe.yaml": [
        ('  members: ["Germany (E1)", "France (E2)"', '  members: ["Germany (E1)", "France (E2)"', "noop anchor"),
        ('  drive: LHD\n  regime: type-approval\n  basis: "EU Whole Vehicle Type Approval',
         '  drive: mixed\n  regime: type-approval\n  basis: "EU Whole Vehicle Type Approval',
         "mk-05 EU drive (IE, MT, CY drive on the left)"),
        ('    - { name: "Serbia — Agency for Safety in Traffic / Ministry of Interior (homologation)", scope: "Vehicle homologation", url: "https://www.abs.gov.rs" }',
         '    - { name: "Serbia — Road Traffic Safety Agency (ABS)", scope: "Vehicle homologation; technical services authorised by the transport ministry", url: "https://www.abs.gov.rs" }',
         "mk-06 BALKANS Serbia authority"),
        ('    - "Kyrgyzstan\'s 1958 Agreement accession was reported in 2025."',
         '    - "Kyrgyzstan is reported as a 1958 Agreement CP (accession reported 21 Aug 2023 — verify at UNECE)."',
         "mk-06 EAEU Kyrgyzstan"),
        ('    - "Uzbekistan\'s 1958 Agreement accession was reported in 2025; Tajikistan is a 1958 Agreement CP — verify current status at UNECE."',
         '    - "Uzbekistan acceded to the 1958 Agreement (reported 20 Oct 2025, also the 1998 Agreement) and Mongolia\'s accession is reported for 29 Apr 2026; Tajikistan and Turkmenistan status not confirmed — verify all at UNECE."',
         "mk-06 CENTRAL-ASIA notes (Tajikistan claim withdrawn)"),
    ],
    "markets/mea.yaml": [
        ('  emissions: "GSO Euro-level limits (MY2027 step to Euro 6-equivalent per GSO plan — verify)"',
         '  emissions: "GSO MY2027 step: Euro 5 limits for Saudi Arabia (Euro 6b applies in the UAE) — per the GSO MY2027 emission-limit record; verify dates"',
         "mk-07 SA emissions"),
        ('  emissions: "Euro 4–6 references per GSO plan"', '  emissions: "Euro 6b under the GSO MY2027 step (reported from Jan 2026 — verify)"', "mk-07 AE emissions"),
        ('  marks: ["ECAS vehicle conformity certificate", "UAE fuel-economy label", "eCall (UAE.S 5019) compliance"]',
         '  marks: ["ECAS vehicle conformity certificate", "UAE fuel-economy label (standard number not verified)", "eCall (UAE.S 5019) compliance"]',
         "mk-07 AE marks"),
        ('  records: [gcc-ecas-moiat-conformity-certificates, gcc-uae-s-5019-2024, gcc-uae-fuel-economy-standard-number-to-verify-gemini-cited-uae-s-5011]',
         '  records: [gcc-ecas-moiat-conformity-certificates, gcc-uae-s-5019-2024]',
         "mk-07 AE records (unverified record deleted)"),
        ('  emissions: "GSO Euro-level limits"\n', '  emissions: "GSO MY2027 step: Euro 5 for Kuwait per the GSO record; Qatar, Bahrain, Oman not verified"\n', "mk-07 GCC-OTHER emissions"),
        ('  name: Jordan, Lebanon, Iraq\n', '  name: Jordan, Lebanon, Iraq, Syria\n', "mk-07 LEVANT gains Syria"),
        ('  aliases: [Jordan, Lebanon, Iraq, JSMO, COSQC]\n  members: [Jordan, Lebanon, Iraq]',
         '  aliases: [Jordan, Lebanon, Iraq, Syria, JSMO, COSQC]\n  members: [Jordan, Lebanon, Iraq, Syria]',
         "mk-07 LEVANT members"),
        ('  process: ["Pre-shipment/import conformity verification; registration."]\n  records: []',
         '  process: ["Pre-shipment/import conformity verification; registration."]\n  notes: ["Syria: US comprehensive sanctions were revoked (EO 14312, effective 1 Jul 2025) and the EU lifted economic sanctions (May 2025); targeted listings and export controls remain — check with trade compliance."]\n  records: []',
         "mk-07 LEVANT Syria note"),
        ('  name: Iran, Syria, North Korea, Cuba, Yemen (restricted / sanctioned)', '  name: Iran, North Korea, Cuba, Yemen (restricted / sanctioned)', "mk-07 SANCTIONED name"),
        ('  aliases: [Iran, Syria, North Korea, Cuba, Yemen]\n  members: [Iran, Syria, North Korea (DPRK), Cuba, Yemen]\n  drive: mixed',
         '  aliases: [Iran, North Korea, Cuba, Yemen]\n  members: [Iran, North Korea (DPRK), Cuba, Yemen]\n  drive: LHD',
         "mk-07 SANCTIONED members/drive"),
        ('  basis: "Comprehensive or sectoral sanctions (US OFAC, EU, UK, UN) restrict vehicle/part exports and engagement"',
         '  basis: "Sanctions restrict vehicle/part exports and engagement — regimes differ: Iran and North Korea (UN, US, EU, UK); Cuba (US embargo only); Yemen (targeted listings)"',
         "mk-07 SANCTIONED basis"),
        ('  un_1958: null\n  un_1998: null\n  authorities:\n    - { name: Standards Organisation of Nigeria (SON)',
         '  un_1958: true\n  un_1998: null\n  authorities:\n    - { name: Standards Organisation of Nigeria (SON)',
         "mk-08 NG un_1958 (E63, verified)"),
        ('  notes: ["Nigeria\'s 1958 Agreement accession status should be checked at UNECE."]',
         '  notes: ["Nigeria is a 1958 Agreement CP (E63); SONCAP remains the import conformity route and does not itself rest on E-mark approvals."]',
         "mk-08 NG notes"),
        ('  members: [Kenya, Tanzania, "Uganda (1958 CP, reported)", Rwanda, Ethiopia]',
         '  members: [Kenya, Tanzania, Uganda, Rwanda, Ethiopia]',
         "mk-08 EAST-AFRICA Uganda claim withdrawn (unconfirmed)"),
        ('  notes: ["Tunisia is a 1958 Agreement CP (E58); Morocco and Algeria status unverified here."]',
         '  notes: ["Tunisia is a 1958 Agreement CP (E58) and reported 1998 Agreement CP; Morocco and Algeria status unverified here."]',
         "mk-08 MAGHREB note"),
    ],
    "glossary.yaml": [
        ('definition: "Canada Motor Vehicle Safety Standards in Schedule IV of the Motor Vehicle Safety Regulations;',
         'definition: "Canada Motor Vehicle Safety Standards in Schedule III of the Motor Vehicle Safety Regulations (C.R.C., c. 1038);',
         "gl-01 CMVSS schedule"),
    ],
    "crosswalk.yaml": [
        ('      US: { cite: "Self-certification — 49 CFR 567 (certification), 566, 565; 49 U.S.C. 30112/30115", records: [us-cfr-part-567, us-cfr-part-566], note: "No pre-market approval; NHTSA audits post-sale." }',
         '      US: { cite: "Self-certification — 49 CFR 567 (certification), 566, 565; 49 U.S.C. 30112/30115", records: [us-cfr-part-567, us-cfr-part-566], note: "No pre-market approval; NHTSA audits post-sale." }',
         "noop anchor"),
        ('records: [au-workbook-reg-0370-road-vehicle-standards-act-2018-road-vehicle-standards-rules-2019, au-workbook-reg-0371-register-of-approved-vehicles-rav, au-f2012l01123] }',
         'records: [au-workbook-reg-0370-road-vehicle-standards-act-2018-road-vehicle-standards-rules-2019, au-workbook-reg-0371-register-of-approved-vehicles-rav] }',
         "cw approval-framework AU (superseded record)"),
        ('      AU: { cite: "Road Vehicle Standards Act 2018 / Rules 2019 — type approval + RAV entry; ADR 00/00 definitions"',
         '      AU: { cite: "Road Vehicle Standards Act 2018 / Rules 2019 — type approval + RAV entry; ADR definitions & vehicle categories"',
         "cw approval-framework AU cite"),
        ('      BR: { cite: "CONTRAN safety labeling / ENCE label", records: [br-contran-safety-labeling] }',
         '      BR: { cite: "CONTRAN vehicle safety label / consumer information (verify instrument)", records: [br-contran-safety-labeling], status: proposed, note: "ENCE is the INMETRO energy-efficiency label, not a compliance label." }',
         "cw-01 certification-label BR"),
        ('      CN: { cite: "Mandatory GB for light-vehicle AEB under development", status: proposed }',
         '      CN: { cite: "GB 39901-2025 (light-vehicle AEBS, mandatory) — new M1 types from 1 Jan 2028; N1 phased later", status: phase-in }',
         "cw-03 aeb CN (verified)"),
        ('      AU: { cite: "ADR 98/02 (car-to-car + pedestrian/cyclist)", records: [au-f2026l00284], status: phase-in }',
         '      AU: { cite: "ADR 98/00–98/02 (car-to-car, pedestrian, then cyclist stages)", records: [au-f2026l00284], status: phase-in }',
         "cw-03 aeb AU"),
        ('      KR: { cite: "KMVSS Art. 53-4", records: [kr-kmvss-art53-4] }',
         '      KR: { cite: "KMVSS Art. 53-4 (school vans for children only)", records: [kr-kmvss-art53-4] }',
         "cw-03 child-presence KR scope"),
        ('      BR: { cite: "CONTRAN 915/2022", records: [br-contran-915] }\n      GCC: { cite: "GSO-ECE 13H"',
         '      GCC: { cite: "GSO-ECE 13H"',
         "cw-03 brakes BR (915/2022 is L-category ABS/CBS)"),
        ('      UN: { cite: "UN R130 (LDWS, heavy); UN R79 (ELKS / corrective steering)", records: [ece-r79] }',
         '      UN: { cite: "No single UN R for M1/N1 ELKS — UN R130 (LDWS) and UN R79 (corrective steering) cover the functions", records: [ece-r79] }',
         "cw-03 lane-keeping UN"),
        ('      JP: { cite: "Safety Regs Art. 32 et seq. (UN R48 applied)", records: [jp-jvsregs-art32] }',
         '      JP: { cite: "Safety Regs lamp-installation articles (UN R48 applied)" }',
         "cw-04 lighting-installation JP (Art. 32 is headlamps)"),
        ('      KR: { cite: "KMVSS Art. 38", records: [kr-kmvss-art38] }\n      AU: { cite: "ADR 46/00; ADR 77/00 (gas discharge)"',
         '      KR: { cite: "KMVSS Art. 38", records: [kr-kmvss-art38] }\n      JP: { cite: "Safety Regs Art. 32 (headlamps)", records: [jp-jvsregs-art32] }\n      AU: { cite: "ADR 46/00; ADR 77/00 (gas discharge)"',
         "cw-04 headlamps JP"),
        ('      BR: { cite: "CONTRAN 924/2022, 966/2022", records: [br-contran-924, br-contran-966] }',
         '      BR: { cite: "CONTRAN 966/2022 (rear-view mirrors)", records: [br-contran-966], note: "CONTRAN 924/2022 adds mirror/camera devices for school-transport vehicles." }',
         "cw-04 indirect-vision BR"),
        ('      CN: { cite: "GB 11562-2025", records: [cn-gb-11562] }',
         '      CN: { cite: "GB 11562-2014 (in force); GB 11562-2025 applies from 1 Jan 2027", records: [cn-gb-11562], status: phase-in }',
         "cw-04 forward-vision CN"),
        ('      BR: { cite: "CONTRAN 758/2018; 37/1998", records: [br-contran-758, br-contran-37] }',
         '      BR: { cite: "CONTRAN 758/2018 (allows UN R121 or FMVSS 101 alternatives)", records: [br-contran-758] }',
         "cw-04 controls-telltales BR"),
        ('      BR: { cite: "CONTRAN 827/1998", records: [br-contran-827] }',
         '      BR: { cite: "CONTRAN 764/2018 (horn sound-pressure test method); horn required by CONTRAN 912/2022", records: [br-contran-764, br-contran-912] }',
         "cw-05 horn BR (827/1998 does not exist)"),
        ('      GCC: { cite: "GSO 1052:2002 (temporary spare)", records: [gcc-gso-1052-2000] }',
         '      GCC: { cite: "GSO 1052:2000 (temporary spare)", records: [gcc-gso-1052-2000] }',
         "cw-05 tyre-installation GCC"),
        ('      GCC: { cite: "GSO-ECE 26; GSO 41", records: [gcc-gso-ece-26, gcc-gso-41-2007] }',
         '      GCC: { cite: "GSO-ECE 26", records: [gcc-gso-ece-26] }',
         "cw-05 external-projections GCC"),
        ('      KR: { cite: "KMVSS Art. 93", records: [kr-kmvss-art93] }\n      UN: { cite: "UN R42',
         '      KR: { cite: "KMVSS Art. 93", records: [kr-kmvss-art93] }\n      GCC: { cite: "GSO 41:2007 (front & rear protective devices)", records: [gcc-gso-41-2007] }\n      UN: { cite: "UN R42',
         "cw-05 bumpers GCC"),
        ('      KR: { cite: "KMVSS Art. 95", records: [kr-kmvss-art95] }\n      CN: { cite: "GB 8410-2006"',
         '      KR: { cite: "KMVSS Art. 95", records: [kr-kmvss-art95] }\n      BR: { cite: "CONTRAN 498/2014 (interior lining flame propagation ≤ 100 mm/min)", records: [br-contran-498] }\n      CN: { cite: "GB 8410-2006"',
         "cw-06 flammability BR"),
        ('      BR: { cite: "CONTRAN 498/2014", records: [br-contran-498] }\n',
         '',
         "cw-06 hood-latch BR removed (498/2014 is flammability; replacement unverified)"),
        ('      JP: { cite: "Safety Regs / TRIAS", records: [jp-srrv-accelerator-control] }',
         '      JP: { cite: "Safety Regs / TRIAS (accelerator control)" }',
         "cw-06 accelerator-control JP record"),
        ('      CN: { cite: "GB 1589-2016 (dimensions, axle loads, masses); GB 7258-2017", records: [cn-gb-1589, cn-gb-7258-2017] }',
         '      CN: { cite: "GB 1589-2016 (dimensions, axle loads, masses); GB 7258-2017", records: [cn-gb-1589, cn-gb-7258-2017], note: "GB 1589-2026 revision reported (applies from 1 Jul 2027) — verify." }',
         "cw-06 dimensions CN"),
        ('      GCC: { cite: "GSO 42:2015 General Requirements", records: [gcc-gso-42-2015] }\n      BR: { cite: "CONTRAN 912/2022 Mandatory Equipment", records: [br-contran-912] }',
         '',
         "cw-06 dimensions GCC/BR (records do not cover dimensions)"),
        ('      US: { cite: "FMVSS 305a (supersedes 305)", records: [us-fmvss-305a, us-fmvss-305] }',
         '      US: { cite: "FMVSS 305 (current); FMVSS 305a mandatory from 1 Sep 2027 (optional earlier)", records: [us-fmvss-305, us-fmvss-305a], status: phase-in }',
         "cw-06 ev-electrical-safety US"),
        ('      IN: { cite: "AIS-038 Rev 2", records: [in-ais-038-rev-2-ais-156] }',
         '      IN: { cite: "AIS-038 Rev 2 (M & N categories)", records: [in-ais-038-rev-2-ais-156] }',
         "cw-06 ev-electrical-safety IN"),
        ('      IN: { cite: "AIS-038 Rev 2 / AIS-156", records: [in-ais-038-rev-2-ais-156] }',
         '      IN: { cite: "AIS-038 Rev 2 (AIS-156 is for L-category only)", records: [in-ais-038-rev-2-ais-156] }',
         "cw-06 reess IN"),
        ('      US: { cite: "40 CFR 86 Subpart S (Tier 3 → 2027+), 40 CFR 1066; CARB LEV IV (13 CCR 1961.4)",',
         '      US: { cite: "40 CFR 86 Subpart S (Tier 3 → 2027+ criteria pollutants), 40 CFR 1066; CARB LEV III (ACC II / LEV IV federal waiver revoked Jun 2025, in litigation)",',
         "cw-06 exhaust-emissions US"),
        ('      US: { cite: "NHTSA CAFE 49 CFR 531/533; EPA GHG 40 CFR 86/600; fuel economy label 40 CFR 600",',
         '      US: { cite: "NHTSA CAFE 49 CFR 531/533 (reset MY2022–2031, FR 30 Sep 2026); fuel-economy test & label 40 CFR 600 (EPA vehicle GHG standards rescinded Feb 2026)",',
         "cw-06 co2-fuel-economy US"),
        ('      KR: { cite: "KMVSS Art. 108-2; average fuel economy / GHG standards", records: [kr-kmvss-art108-2] }',
         '      KR: { cite: "KMVSS Art. 108-2 (fuel-economy label accuracy); fleet fuel-economy/GHG standards are a separate instrument", records: [kr-kmvss-art108-2] }',
         "cw-06 co2 KR"),
        ('      CN: { cite: "GB 34660 (vehicle EMC)", records: [cn-gb-34660] }',
         '      CN: { cite: "GB 34660-2017 (in force); GB 34660-2026 from 1 Jul 2027", records: [cn-gb-34660] }',
         "cw-07 emc CN"),
        ('      EU: { cite: "ELV Directive 2000/53/EC; REACH (EC) 1907/2006; Battery Dir./Reg.", records: [eu-32000l0053, eu-32006r1907, eu-32006l0066] }',
         '      EU: { cite: "ELV Directive 2000/53/EC (ELV Regulation adopted to replace it); REACH (EC) 1907/2006; Batteries Regulation (EU) 2023/1542 (replaced Dir. 2006/66/EC from 18 Aug 2025)", records: [eu-32000l0053, eu-32023r1542] }',
         "cw-07 end-of-life EU"),
        ('      US: { cite: "40 CFR 82 Subpart G (SNAP); AIM Act HFC phasedown", records: [us-40cfr-part-82] }',
         '      US: { cite: "40 CFR 82 Subpart G (SNAP); AIM Act HFC rules in 40 CFR 84", records: [us-40cfr-part-82] }',
         "cw-07 mac-refrigerant US"),
        ('      IN: { cite: "AIS-100" }',
         '      IN: { cite: "AIS-100 (Rev. 1 aligned with UN R127 / GTR 9 — notification status to verify)", status: proposed }',
         "cw-02 pedestrian IN"),
        ('      CN: { cite: "GB 11551-2014", records: [cn-gb-11551-2014] }',
         '      CN: { cite: "GB 11551-2014 (100 % overlap rigid barrier, 50 km/h)", records: [cn-gb-11551-2014] }',
         "cw-01 frontal-full CN (reviewer finding rejected; cite clarified)"),
        ('      KR: { cite: "KMVSS Art. 92", records: [kr-kmvss-art92] }\n      GCC: { cite: "GSO 39:2005"',
         '      KR: { cite: "KMVSS Art. 92", records: [kr-kmvss-art92] }\n      CN: { cite: "GB 26134 (roof crush resistance of passenger cars; 2024 revision reported from 1 Jul 2025 — verify)" }\n      GCC: { cite: "GSO 39:2005"',
         "cw-01 roof-crush CN"),
    ],
}


def main() -> None:
    log = ["\n## Phase 1/3 — knowledge-layer fixes (markets, crosswalk, glossary)\n", "| File | Finding | Change |", "|---|---|---|"]
    for rel, edits in EDITS.items():
        path = K / rel
        text = path.read_text(encoding="utf-8")
        for old, new, ref in edits:
            n = text.count(old)
            if n != 1:
                raise SystemExit(f"{rel}: anchor matched {n}x for [{ref}]: {old[:90]!r}")
            text = text.replace(old, new)
            if old != new:
                log.append(f"| `{rel}` | {ref} | applied |")
        path.write_text(text, encoding="utf-8")
    changes = ROOT / "review" / "CHANGES.md"
    with changes.open("a", encoding="utf-8") as fh:
        fh.write("\n".join(log) + "\n")
    print(f"applied {len(log) - 3} knowledge edits")


if __name__ == "__main__":
    main()
